name: Publish Package1

on:
  push:
    branches:
      - main  # 或者你的主要分支名称

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --prefix ./workspaces/json2interface-web

      - name: Build json2interface-web
        run: npm run build --prefix ./workspaces/json2interface-web

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          if git rev-parse --verify origin/gh-pages; then
            git checkout gh-pages
            git pull origin gh-pages
          else
            git checkout --orphan gh-pages
          fi
          rm -rf ./*
          cp -r ./workspaces/json2interface-web/dist/* ./
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
